export const PATIENT_PORTAL_ENCOUNTER_TAB = [
  {
    id: "summary",
    label: "Summary",
    category: "summary",
    isDefault: true,
    order: 1,
  },
  {
    id: "interview_review_of_systems",
    label: "Review of Systems",
    category: "interview",
    isDefault: true,
    order: 1,
  },
  {
    id: "interview_medical_history",
    label: "Medical History",
    category: "interview",
    isDefault: false,
    order: 2,
  },
  {
    id: "interview_surgical_history",
    label: "Surgical History",
    category: "interview",
    isDefault: false,
    order: 3,
  },
  {
    id: "interview_social_history",
    label: "Social History",
    category: "interview",
    isDefault: false,
    order: 4,
  },
  {
    id: "interview_ob_gyne_history",
    label: "OB-Gyne History",
    category: "interview",
    isDefault: false,
    order: 5,
  },
  {
    id: "interview_immunizations",
    label: "Immunizations",
    category: "interview",
    isDefault: false,
    order: 6,
  },
  {
    id: "interview_ncd",
    label: "NCD High-Risk Assessment",
    category: "interview",
    isDefault: false,
    order: 7,
  },
  {
    id: "vitals",
    label: "Vitals & Measurements",
    category: "vitals",
    isDefault: true,
    order: 1,
  },
  {
    id: "vitals_pertinent_findings",
    label: "Miscellaneous",
    category: "vitals",
    isDefault: false,
    order: 2,
  },
  {
    id: "consultation_atc",
    label: "ATC",
    category: "consultation",
    isDefault: true,
    order: 1,
  },
  {
    id: "consultation_chief_complaint",
    label: "Subjective/History of Illness",
    category: "consultation",
    isDefault: false,
    order: 2,
  },
  {
    id: "consultation_objective",
    label: "Objective/Physical Examination",
    category: "consultation",
    isDefault: false,
    order: 3,
  },
  {
    id: "consultation_assessment",
    label: "Assessment/Diagnosis",
    category: "consultation",
    isDefault: false,
    order: 4,
  },
  {
    id: "consultation_plan",
    label: "Plan/Management",
    category: "consultation",
    isDefault: false,
    order: 5,
  },
  {
    id: "laboratory_diagnosis",
    label: "Diagnosis",
    category: "laboratory",
    isDefault: true,
    order: 1,
  },
  {
    id: "prescription_medications",
    label: "Medications",
    category: "prescription",
    isDefault: true,
    order: 1,
  },
  {
    id: "documents_all",
    label: "All Documents",
    category: "documents",
    isDefault: true,
    order: 1,
  },
  {
    id: "documents_xml_viewer",
    label: "XML Viewer",
    category: "documents",
    isDefault: false,
    order: 2,
  },
  {
    id: "queue_create",
    label: "Create",
    category: "queue",
    isDefault: true,
    order: 1,
  },
  {
    id: "queue_progress",
    label: "Progress",
    category: "queue",
    isDefault: false,
    order: 2,
  },
];

export const PATIENT_PORTAL_TAB = {
  DEFAULT_TABS: ["Encounters", "Appointments", "Transactions", "Extensions"],
  PERSONAL_INFO: ["Information"],
  ENCOUNTER: PATIENT_PORTAL_ENCOUNTER_TAB,
};

export const ENCOUNTER_FEATURES_TAB = [
  {
    id: "tranche_validator",
    name: "Validator",
    description: "Validate the tranche of the member.",
    isEnabled: true,
    index: 0,
    userTypes: ["admin", "hci", "physician", "presenter"],
  },
  {
    id: "submit_report",
    name: "Progress",
    description: "View the progress of the encounter.",
    isEnabled: true,
    index: 1,
    userTypes: ["admin", "hci", "physician", "presenter"],
  },
];
